# Xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'
name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'

steps:

- task: Xcode@5
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'macosx10.15'
    xcWorkspacePath: 'native/SignPostWrapper.xcodeproj'
    packageApp: false
    destinationPlatformOption: 'macOS'

- task: CopyFiles@2
  inputs:
    contents: '$(build.SourcesDirectory)/native/build/Release/libSignPostWrapper.dylib'
    targetFolder: '$(build.SourcesDirectory)/dotnet/Xamarin.Mac.SignPostWrapper/'
    OverWrite: true
    flattenFolders: true

- task: DownloadSecureFile@1]
  name: signpostwrapper
  inputs:
    secureFile: 'signpostwrapper.snk'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Xamarin.Mac.SignPostWrapper.csproj'
    arguments: '-p:Configuration=Release'

- task: CmdLine@2
  inputs:
    script: 'sn -R  $(build.SourcesDirectory)/dotnet/Xamarin.Mac.SignPostWrapper/bin/Release/netstandard2.0/Xamarin.Mac.SignPostWrapper.dll $(signpostwrapper.secureFilePath)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Xamarin.Mac.SignPostWrapper.csproj'
    configuration: 'Release'
    nobuild: true
    versioningScheme: 'byBuildNumber'

- task: CopyFiles@2
  inputs:
    contents: '**/*.nupkg'
    targetFolder: '$(build.ArtifactsDirectory}'

- task: PublishBuildArtifacts@1

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'VSECFeed'
    
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'VSECFeed'

- task: DotNetCoreCLI@2
  displayName: Push Nuget Package
  inputs:
    command: custom
    custom: nuget
    arguments: >
      push $(Build.ArtifactStagingDirectory)/*.nupkg
      -s https://api.nuget.org/v3/index.json
      -k $(NuGet_APIKEY)
      -n true