# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'macosx10.15'
    configuration: 'Release clean build'
    xcWorkspacePath: 'native/SignPostWrapper.xcodeproj'

- task: CopyFiles@2
  inputs:
    contents: '**/*.dylib'
    targetFolder: '$(build.SourcesDirectory)/dotnet/Xamarin.Mac.SignPostWrapper'

- task: XamariniOS@2
  inputs:
    solutionFile: '**/Xamarin.Mac.SignPostWrapper.csproj'
    configuration: '$(buildConfiguration)'
    packageApp: true
    buildForSimulator: false

- task: PublishBuildArtifacts@1
