# Xcode


# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'
name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'

steps:

- task: Xcode@5
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'macosx10.15'
    xcWorkspacePath: 'native/SignPostWrapper.xcodeproj'
    packageApp: false
    destinationPlatformOption: 'macOS'

- task: CopyFiles@2
  inputs:
    contents: '$(build.SourcesDirectory)/native/build/Release/libSignPostWrapper.dylib'
    targetFolder: '$(build.SourcesDirectory)/dotnet/Xamarin.Mac.SignPostWrapper/'
    OverWrite: true
    flattenFolders: true
    
- task: MSBuild@1
  inputs:
    solution: '$(build.SourcesDirectory)/dotnet/Xamarin.Mac.SignPostWrapper/Xamarin.Mac.SignPostWrapper.csproj'
    configuration: 'Release'
    clean: false

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(build.SourcesDirectory)/dotnet/Xamarin.Mac.SignPostWrapper/Xamarin.Mac.SignPostWrapper.csproj'
    configuration: 'Release'
    versioningScheme: 'byBuildNumber'

- task: CopyFiles@2
  inputs:
    contents: '**/*.nupkg'
    targetFolder: '$(build.ArtifactsDirectory}'

- task: PublishBuildArtifacts@1

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'VSECFeed'
    
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'VSECFeed'

- task: UseDotNet@2 
- script: dotnet nuget push --api-key $(NuGet_APIKEY) --source https://api.nuget.org/v3/index.json *.nupkg